server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true

spring:
  datasource:
    url: postgresql://twst_user:njomu5ZOaOuUxstSFD3WaoZXuwb8Wia0@dpg-d084ul7diees738tkjm0-a/twst # 接続先URL
    username: twst_user # ユーザー名
    password: njomu5ZOaOuUxstSFD3WaoZXuwb8Wia0 # パスワード
    driverClassName: org.postgresql.Driver
tymeleaf:
  chache: false #リアルタイム反映
  prefix: file:src/main/resources/templates/
  mode: html
springdoc:
  cache:
    disabled: true
  api-docs:
    enabled: true
logging:
  level: #ログレベル
    org:
    springframework: DEBUG
  root: DEBUG
  ROOT: DEBUG
  com.zaxxer.hikari: debug
  # your:
  #  package: DEBUG
