server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/twst?currentSchema=schema01 # 接続先URL
    username: user01 # ユーザー名
    password: password # パスワード
    driverClassName: org.postgresql.Driver
tymeleaf:
  chache: false #リアルタイム反映
  prefix: file:src/main/resources/templates/
  mode: html
springdoc:
  cache:
    disabled: true
  api-docs:
    enabled: true
logging:
  level: #ログレベル
    org:
    springframework: DEBUG
  root: DEBUG
  ROOT: DEBUG
  com.zaxxer.hikari: debug
  # your:
  #  package: DEBUG
