myapp:
  config:
    env: prod

spring:
  datasource:
    url: ${DATABASE_URL} # 接続先URL
    username: ${DATABASE_USERNAME} # ユーザー名
    password: ${DATABASE_PASSWORD} # パスワード
    driverClassName: org.postgresql.Driver
    schemas: ${SCHEMAS} # スキーマ
    hikari:
      connection-test-query: select current_schema();SET search_path = schema01;
      idle-timeout: 100000
      max-lifetime: 120000
