server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/twst?currentSchema=schema01 # 接続先URL
    username: user01 # ユーザー名
    password: password # パスワード
    driverClassName: org.postgresql.Driver
thymeleaf:
  prefix: file:src/main/resources/templates/
  suffix: .html
  mode: html
  encoding: UTF-8
  check-template: false
  check-template-location: false
  enabled: true
springdoc:
  cache:
    disabled: true
  api-docs:
    enabled: true
logging:
  level: #ログレベル
    org:
    springframework: DEBUG
    web: DEBUG
  root: DEBUG
  ROOT: DEBUG
  com.zaxxer.hikari: DEBUG
  # your:
  #  package: DEBUG
